# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'SwiftGoogleSheets' do
  # Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

  # Pods for SwiftGoogleSheets

  pod 'GoogleSignIn'
  pod 'GoogleAPIClientForREST/Core'
  pod 'GoogleAPIClientForREST/Sheets'
  pod 'Toast-Swift'

end
